export const data = {
    "_id": {
        "$oid": "623d183ff86bd06cafea600e"
      },
      "_t": [
        "ActiveDirectoryModelBase",
        "Event4624Model"
      ],
      "agentDevice": "WindowsLog",
      "agentLogFile": "Security",
      "pluginVersion": "7.2.9.105",
      "source": "Microsoft-Windows-Security-Auditing",
      "computerName": "L3-DC10.stella.local",
      "originatingComputer": "10.0.4.10",
      "user": null,
      "domain": null,
      "eventID": 4624,
      "eventType": null,
      "eventCategory": 12544,
      "recordNumber": 33763570,
      "timeGenerated": 0,
      "timeWritten": 0,
      "level": "Log Always",
      "keywords": null,
      "task": "SE_ADT_LOGON_LOGON",
      "opCode": "Info",
      "message": "An account was successfully logged on.",
      "sourceip": "10.0.5.88",
      "time": {
        "$date": {
          "$numberLong": "1667660312000"
        }
      },
      "epochTime": {
        "$numberLong": "1667660312000"
      },
      "keyWords": "Audit Success",
      "packageName": "NTLM V2",
      "newLogonID": "0xD4E8ED0",
      "logsourceTime": 1636095548,
      "subjectLogonID": "0x0",
      "subjectLogonType": "3",
      "subject": null,
      "subjectSecurityID": "NULL SID",
      "subjectAccountName": "-",
      "subjectAccountDomain": "-",
      "logonID": null,
      "logonInformation": null,
      "logonType": null,
      "restrictedAdminMode": null,
      "virtualAccount": null,
      "elevatedToken": null,
      "impersonationLevel": null,
      "newLogon": null,
      "newLogonSecurityID": "STELLA\\sumit.k",
      "newLogonAccountName": "sumit.k",
      "newLogonAccountDomain": "STELLA",
      "newLogonLogonID": null,
      "linkedLogonID": "0x0",
      "networkAccountName": null,
      "networkAccountDomain": null,
      "logonGUID": "{00000000-0000-0000-0000-000000000000}",
      "processInformation": null,
      "processID": "0x0",
      "processName": null,
      "networkInformation": null,
      "workstationName": "QDS8",
      "sourceNetworkAddress": "10.0.5.88",
      "sourcePort": 50940,
      "detailedAuthenticationInformation": null,
      "logonProcess": "NtLmSsp",
      "authenticationPackage": "NTLM",
      "transitedServices": null,
      "ntmlPackageName": null,
      "keyLength": null
}